spring:
  application:
    name: SpringBootStudentMicroService-Client
  web:
    error:
      whitelabel:
        enabled: false
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
server:
  port: 1214
